CREATE TABLESPACE uminho_tables DATAFILE 'UMINHO_FILES_01.dbf' SIZE 500m;

CREATE USER uminho IDENTIFIED BY "uminho2020" DEFAULT TABLESPACE uminho_tables QUOTA
UNLIMITED ON uminho_tables;


GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SEQUENCE TO uminho;

CREATE TABLESPACE uminho_tables DATAFILE 'UMINHO_FILES_01.dbf' SIZE 500m;

/*------------------*/
CREATE TABLESPACE doente_tables DATAFILE 'DOENTE_FILES_01.dbf' SIZE 500m;

CREATE USER doente IDENTIFIED BY "uminh02020" DEFAULT TABLESPACE doente_tables QUOTA
UNLIMITED ON doente_tables;


GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SEQUENCE TO doente;

/*--------------------------*/
CREATE TABLESPACE music_tablespace DATAFILE 'music_files_01.dbf' SIZE 200m;

CREATE USER music IDENTIFIED BY "music2020" DEFAULT TABLESPACE music_tablespace QUOTA
UNLIMITED ON music_tablespace;

GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SEQUENCE TO music;


/*-------------------------------*/

/*TP prático */
CREATE TABLESPACE HR_tables DATAFILE 'HR_FILES_02.dbf' SIZE 500m;

CREATE USER HR IDENTIFIED BY "hr2022" DEFAULT TABLESPACE HR_tables QUOTA
UNLIMITED ON HR_tables;


GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SEQUENCE TO HR;

